FROM python:3.12-slim AS base

RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        git \
        ca-certificates && \
    apt-get clean

# Installer Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app
COPY . .

RUN poetry config virtualenvs.create false
